[project]
name = "gds-eligibility-buddy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.3.22",
    "google-adk>=1.18.0",
    "google-generativeai>=0.8.6",
    "litellm>=1.80.12",
    "openai>=2.14.0",
    "python-dotenv>=1.2.1",
    "boto3>=1.40.70",
]
